#custom:
#  secondary-datasource:
#    url: jdbc:postgresql://localhost:5430/testing2
#    username: zourkas2
#    password: rooting2
#    hikari:
#      jdbc-url: jdbc:postgresql://localhost:5430/testing2
#      leak-detection-threshold: 24000
#      maximum-pool-size: 20
#      minimum-idle: 5
#  jpa:
#    hibernate:
#      ddl-auto: update
#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#
#spring:
#  config:
#    activate:
#      on-profile: dev
